import {
  Patient,
  StaffMember,
  DailyMetrics,
  SOPDocument,
  ChecklistItem,
} from "./types";

// ─── PATIENTS ───────────────────────────────────────────────────────────────

export const mockPatients: Patient[] = [
  // RECALL patients
  {
    id: "r001",
    patientName: "Emma Rodriguez",
    guardianName: "Maria Rodriguez",
    phone: "(602) 555-0142",
    insurance: "Delta Dental PPO",
    dob: "2015-03-14",
    lastVisit: "2023-11-08",
    provider: "Dr. Patel",
    assignedStaff: "Lesley",
    priority: "critical",
    status: "attempted",
    daysOverdue: 198,
    estimatedValue: 285,
    attemptCount: 2,
    nextStep: "Call again — 3rd attempt triggers escalation",
    notes: "Mom prefers morning calls. Left VM twice.",
    workflow: "recall",
    recallType: "Prophy + Exam",
  },
  {
    id: "r002",
    patientName: "Liam Chen",
    guardianName: "Jennifer Chen",
    phone: "(480) 555-0287",
    insurance: "Cigna DHMO",
    dob: "2018-07-22",
    lastVisit: "2023-12-15",
    provider: "Dr. Nguyen",
    assignedStaff: "Ashley",
    priority: "high",
    status: "new",
    daysOverdue: 163,
    estimatedValue: 320,
    attemptCount: 0,
    nextStep: "First outreach call — no contact yet",
    notes: "No prior contact attempts.",
    workflow: "recall",
    recallType: "Prophy + Exam + X-Rays",
  },
  {
    id: "r003",
    patientName: "Sofia Martinez",
    guardianName: "Carlos Martinez",
    phone: "(623) 555-0391",
    insurance: "BlueCross BlueShield",
    dob: "2014-01-09",
    lastVisit: "2024-01-20",
    provider: "Dr. Patel",
    assignedStaff: "Lesley",
    priority: "high",
    status: "in-progress",
    daysOverdue: 127,
    estimatedValue: 265,
    attemptCount: 1,
    nextStep: "Text follow-up — call attempt made 2 days ago",
    notes: "Dad answered briefly, said he'd call back. Sent text.",
    workflow: "recall",
    recallType: "Prophy + Fluoride",
  },
  {
    id: "r004",
    patientName: "Aiden Thompson",
    guardianName: "Sarah Thompson",
    phone: "(520) 555-0458",
    insurance: "Aetna PPO",
    dob: "2016-09-30",
    lastVisit: "2024-02-11",
    provider: "Dr. Nguyen",
    assignedStaff: "Ashley",
    priority: "medium",
    status: "new",
    daysOverdue: 105,
    estimatedValue: 245,
    attemptCount: 0,
    nextStep: "First contact attempt — warm recall call",
    notes: "",
    workflow: "recall",
    recallType: "Prophy + Exam",
  },
  {
    id: "r005",
    patientName: "Olivia Kim",
    guardianName: "Grace Kim",
    phone: "(602) 555-0567",
    insurance: "United Concordia",
    dob: "2019-05-18",
    lastVisit: "2024-03-05",
    provider: "Dr. Patel",
    assignedStaff: "Lesley",
    priority: "medium",
    status: "attempted",
    daysOverdue: 83,
    estimatedValue: 310,
    attemptCount: 1,
    nextStep: "Send text — busy signal on call attempt",
    notes: "Young patient, mom works days. Try evenings.",
    workflow: "recall",
    recallType: "Prophy + X-Rays + Fluoride",
  },
  {
    id: "r006",
    patientName: "Noah Williams",
    guardianName: "Jessica Williams",
    phone: "(480) 555-0634",
    insurance: "MetLife PPO",
    dob: "2013-11-27",
    lastVisit: "2024-03-22",
    provider: "Dr. Nguyen",
    assignedStaff: "Ashley",
    priority: "low",
    status: "scheduled",
    daysOverdue: 66,
    estimatedValue: 295,
    attemptCount: 2,
    nextStep: "Appointment set for June 18 — confirm 48 hrs prior",
    notes: "Scheduled! Confirm appointment next week.",
    workflow: "recall",
    recallType: "Prophy + Exam",
  },

  // TREATMENT patients
  {
    id: "t001",
    patientName: "Isabella Davis",
    guardianName: "Robert Davis",
    phone: "(602) 555-0712",
    insurance: "Delta Dental PPO",
    dob: "2012-08-14",
    lastVisit: "2024-04-10",
    provider: "Dr. Patel",
    assignedStaff: "Lesley",
    priority: "critical",
    status: "in-progress",
    daysOverdue: 52,
    estimatedValue: 1840,
    attemptCount: 1,
    nextStep: "Call to review pre-auth approval & schedule",
    notes: "Pre-auth approved! Parent hesitant about cost.",
    workflow: "treatment",
    treatmentPlan: "4 fillings, 2 crowns (D, E teeth)",
    insuranceEstimate: 1240,
    preAuthStatus: "approved",
  },
  {
    id: "t002",
    patientName: "Mason Johnson",
    guardianName: "Linda Johnson",
    phone: "(480) 555-0823",
    insurance: "Cigna DHMO",
    dob: "2011-02-19",
    lastVisit: "2024-03-28",
    provider: "Dr. Nguyen",
    assignedStaff: "Ashley",
    priority: "high",
    status: "new",
    daysOverdue: 65,
    estimatedValue: 2200,
    attemptCount: 0,
    nextStep: "Review provider notes, then call guardian",
    notes: "Large treatment plan. Insurance pre-auth pending.",
    workflow: "treatment",
    treatmentPlan: "Space maintainer, 3 extractions, sealants x6",
    insuranceEstimate: 1600,
    preAuthStatus: "pending",
  },
  {
    id: "t003",
    patientName: "Ava Anderson",
    guardianName: "Patricia Anderson",
    phone: "(623) 555-0945",
    insurance: "BlueCross BlueShield",
    dob: "2017-06-03",
    lastVisit: "2024-04-15",
    provider: "Dr. Patel",
    assignedStaff: "Lesley",
    priority: "high",
    status: "attempted",
    daysOverdue: 47,
    estimatedValue: 680,
    attemptCount: 2,
    nextStep: "Offer payment plan option — barrier is out-of-pocket",
    notes: "Mom concerned about $440 OOP. Discuss Care Credit.",
    workflow: "treatment",
    treatmentPlan: "2 composite fillings, fluoride varnish",
    insuranceEstimate: 240,
    preAuthStatus: "not-required",
  },
  {
    id: "t004",
    patientName: "Ethan Brown",
    guardianName: "Michael Brown",
    phone: "(520) 555-1056",
    insurance: "Aetna PPO",
    dob: "2010-12-07",
    lastVisit: "2024-05-01",
    provider: "Dr. Nguyen",
    assignedStaff: "Ashley",
    priority: "medium",
    status: "new",
    daysOverdue: 30,
    estimatedValue: 950,
    attemptCount: 0,
    nextStep: "First call — urgent treatment per provider notes",
    notes: "Provider flagged urgency — do not delay.",
    workflow: "treatment",
    treatmentPlan: "Pulpotomy #K, stainless steel crown",
    insuranceEstimate: 680,
    preAuthStatus: "pending",
  },

  // CLAIMS patients
  {
    id: "c001",
    patientName: "Mia Garcia",
    guardianName: "Ana Garcia",
    phone: "(602) 555-1123",
    insurance: "Delta Dental PPO",
    dob: "2014-04-22",
    lastVisit: "2024-02-14",
    provider: "Dr. Patel",
    assignedStaff: "Lesley",
    priority: "critical",
    status: "in-progress",
    daysOverdue: 107,
    estimatedValue: 1240,
    attemptCount: 3,
    nextStep: "Call payer — reference #DDL-2024-8843 — resubmit w/ narrative",
    notes: "Denied: missing narrative. Resubmitting with Dr. note.",
    workflow: "claims",
    claimNumber: "DDL-2024-8843",
    claimDate: "2024-02-16",
    payerName: "Delta Dental of Arizona",
    denialReason: "Missing supporting documentation / narrative",
    claimAmount: 1240,
  },
  {
    id: "c002",
    patientName: "James Wilson",
    guardianName: "Thomas Wilson",
    phone: "(480) 555-1234",
    insurance: "Cigna DHMO",
    dob: "2013-09-15",
    lastVisit: "2024-03-01",
    provider: "Dr. Nguyen",
    assignedStaff: "Ashley",
    priority: "high",
    status: "new",
    daysOverdue: 91,
    estimatedValue: 875,
    attemptCount: 0,
    nextStep: "Open payer portal — check status of claim #CIG-44291",
    notes: "No response received. Check payer portal first.",
    workflow: "claims",
    claimNumber: "CIG-44291",
    claimDate: "2024-03-05",
    payerName: "Cigna Healthcare",
    denialReason: "Pending review",
    claimAmount: 875,
  },
  {
    id: "c003",
    patientName: "Charlotte Moore",
    guardianName: "Rebecca Moore",
    phone: "(623) 555-1345",
    insurance: "Aetna PPO",
    dob: "2016-01-30",
    lastVisit: "2024-03-18",
    provider: "Dr. Patel",
    assignedStaff: "Lesley",
    priority: "high",
    status: "escalated",
    daysOverdue: 74,
    estimatedValue: 2100,
    attemptCount: 4,
    nextStep: "Escalated to manager — 4 attempts, no resolution",
    notes: "Escalated to Vanessa. High-value claim, complex denial.",
    workflow: "claims",
    claimNumber: "AET-2024-9921",
    claimDate: "2024-03-20",
    payerName: "Aetna Life Insurance",
    denialReason: "Service not covered under plan — requires appeal",
    claimAmount: 2100,
  },
  {
    id: "c004",
    patientName: "Benjamin Taylor",
    guardianName: "David Taylor",
    phone: "(520) 555-1456",
    insurance: "MetLife PPO",
    dob: "2015-07-11",
    lastVisit: "2024-04-02",
    provider: "Dr. Nguyen",
    assignedStaff: "Ashley",
    priority: "medium",
    status: "in-progress",
    daysOverdue: 59,
    estimatedValue: 560,
    attemptCount: 1,
    nextStep: "Verify attachments were received — call payer",
    notes: "Attachments sent. Payer confirming receipt.",
    workflow: "claims",
    claimNumber: "MET-88234",
    claimDate: "2024-04-04",
    payerName: "MetLife Insurance",
    denialReason: "Awaiting X-ray attachment",
    claimAmount: 560,
  },
];

// ─── CHECKLISTS ──────────────────────────────────────────────────────────────

export const recallChecklist: ChecklistItem[] = [
  {
    id: "rc1",
    label: "Call patient",
    completed: false,
    steps: [
      "Confirm patient is active and overdue in Open Dental",
      "Review treatment plan and any outstanding care",
    ],
    script: `"Hi Mrs. [parent last name], this is [staff's name] from Memorial Children's Dentistry. We hope [patient's name] has been doing well! We noticed we haven't seen them in a while and wanted to check in. We'd love to help get her back on track with preventive care whenever you're ready. Please give us a call at 281-730-8080. We look forward to hearing from you."`,
  },
  {
    id: "rc4",
    label: "If no answer, send text message",
    completed: false,
    script: `Hi! It's Memorial Children's Dentistry. We haven't seen {{names}} in a while and wanted to check in. We hope they've been doing well! If you'd like to schedule a visit, we're always happy to help. If you've moved, found another dentist, or no longer wish to receive reminders, just let us know so we can update our records. 😊`,
  },
  { id: "rc6", label: "Document communication in commlog", completed: false },
];

export const treatmentChecklist: ChecklistItem[] = [
  {
    id: "tc1",
    label: "Review chart before calling",
    completed: false,
    steps: [
      "Open patient in Open Dental — confirm treatment plan is still unscheduled",
      "Note treatment plan total and what procedures are included",
      "Check insurance remaining benefit (amountRemainingInd) and carrier",
      "Flag as VIP if annual max ≥ $2,000 and plan is > $1,000 — handle with extra care",
      "Check commlog for any prior contact attempts or parent concerns",
    ],
  },
  {
    id: "tc2",
    label: "Call guardian",
    completed: false,
    steps: [
      "Lead with care, not sales — the doctor recommends this for a reason",
      "Acknowledge the parent's time and reassure, never pressure",
      "For VIP families: use first name, reference their specific plan warmly",
      "Mention insurance coverage first to ease financial anxiety",
    ],
    script: `"Hi [parent's name], this is [staff's name] calling from Memorial Children's Dentistry. Dr. [provider] wanted us to reach out because [patient's name] has a treatment plan on file that we'd love to help get scheduled. We know life gets busy, so we just wanted to check in and see how [patient's name] is doing and if there's anything we can help with to make it easier to come in. We have some great appointment times available, and your insurance [carrier name] should cover a good portion of the visit. No pressure at all — we just care about [patient's name]'s smile and want to make sure they're comfortable and healthy!"`,
  },
  {
    id: "tc3",
    label: "If no answer, leave a warm voicemail",
    completed: false,
    script: `"Hi [parent's name], this is [staff's name] from Memorial Children's Dentistry. We're reaching out because [patient's name] has a treatment plan on file and we just wanted to make sure they're doing well. We'd love to connect and help get that scheduled at your convenience — no rush at all. Feel free to give us a call at 281-730-8080 whenever works for you. We look forward to hearing from you. Have a wonderful day!"`,
  },
  {
    id: "tc4",
    label: "If still no response after 2 days, send a text",
    completed: false,
    script: `Hi! It's Memorial Children's Dentistry reaching out about [patient's name]'s treatment plan. We just want to make sure they're doing well and that we can help get their care scheduled at a time that works for your family. No rush — just give us a call at 281-730-8080 or reply here whenever you're ready. We're always happy to help! 😊`,
  },
  {
    id: "tc5",
    label: "Document in commlog",
    completed: false,
    steps: [
      "Log outcome: reached / left voicemail / sent text / no response",
      "Note any parent concerns (cost, scheduling, anxiety, etc.)",
      "If scheduled: note date and time",
      "If declined: note reason and set a 30-day follow-up task",
    ],
  },
];

export const claimsChecklist: ChecklistItem[] = [
  { id: "cc1", label: "Open insurance aging report in Open Dental", completed: false },
  { id: "cc2", label: "Confirm claim submission date & claim number", completed: false },
  { id: "cc3", label: "Check payer portal for current status", completed: false },
  { id: "cc4", label: "Review denial code / EOB reason", completed: false },
  { id: "cc5", label: "Verify all attachments & narratives submitted", completed: false },
  { id: "cc6", label: "Call insurance if no portal resolution", completed: false },
  { id: "cc7", label: "Document reference number in commlog", completed: false },
  { id: "cc8", label: "Correct errors and resubmit claim", completed: false },
  { id: "cc9", label: "Set 14-day follow-up task", completed: false },
];

// ─── STAFF ───────────────────────────────────────────────────────────────────

export const mockStaff: StaffMember[] = [
  {
    id: "vanessa",
    name: "Vanessa",
    role: "Office Manager",
    initials: "V",
    color: "#7C3AED",
    assignedTasks: 12,
    completedToday: 8,
    pending: 3,
    overdue: 1,
    revenueRecovered: 4820,
    dailyScore: 91,
  },
  {
    id: "lesley",
    name: "Lesley",
    role: "Front Desk",
    initials: "L",
    color: "#2563EB",
    assignedTasks: 18,
    completedToday: 11,
    pending: 5,
    overdue: 2,
    revenueRecovered: 3140,
    dailyScore: 84,
  },
  {
    id: "jen",
    name: "Jen",
    role: "Front Desk",
    initials: "J",
    color: "#0891B2",
    assignedTasks: 15,
    completedToday: 9,
    pending: 4,
    overdue: 2,
    revenueRecovered: 2680,
    dailyScore: 78,
  },
  {
    id: "idalia",
    name: "Idalia",
    role: "Front Desk",
    initials: "I",
    color: "#16A34A",
    assignedTasks: 14,
    completedToday: 7,
    pending: 5,
    overdue: 2,
    revenueRecovered: 2100,
    dailyScore: 74,
  },
];

// ─── DAILY METRICS ───────────────────────────────────────────────────────────

export const mockDailyMetrics: DailyMetrics = {
  callsMade: 24,
  callsGoal: 40,
  textsSent: 18,
  textsGoal: 25,
  appointmentsScheduled: 7,
  appointmentsGoal: 12,
  claimsResolved: 3,
  claimsGoal: 8,
  treatmentScheduled: 4,
  treatmentGoal: 6,
  revenueRecovered: 10640,
  revenueGoal: 22000,
};

// ─── SOP DOCUMENTS ───────────────────────────────────────────────────────────

export const mockSOPs: SOPDocument[] = [
  {
    id: "sop1",
    title: "Overdue Recall SOP",
    description: "Step-by-step protocol for contacting and scheduling overdue recall patients",
    workflow: "recall",
    attached: true,
    lastUpdated: "2024-05-01",
    fileSize: "124 KB",
  },
  {
    id: "sop2",
    title: "Unscheduled Treatment SOP",
    description: "Workflow for converting treatment finder cases to scheduled appointments",
    workflow: "treatment",
    attached: true,
    lastUpdated: "2024-04-15",
    fileSize: "98 KB",
  },
  {
    id: "sop3",
    title: "Aging Claims SOP",
    description: "Insurance claim recovery process from aging report to resubmission",
    workflow: "claims",
    attached: false,
  },
  {
    id: "sop4",
    title: "Call Scripts + Text Templates",
    description: "Pre-approved language for calls, texts, and commlog notes",
    workflow: "all",
    attached: true,
    lastUpdated: "2024-05-10",
    fileSize: "76 KB",
  },
];

// ─── AI ACTIONS ──────────────────────────────────────────────────────────────

export const getAIOutput = (action: string, patient: Patient | null): string => {
  const name = patient?.patientName ?? "Patient";
  const guardian = patient?.guardianName ?? "Guardian";
  const phone = patient?.phone ?? "(xxx) xxx-xxxx";
  const insurance = patient?.insurance ?? "Insurance";

  switch (action) {
    case "recall-text":
      return `Hi ${guardian}! This is DentBooks Dental calling for ${name}. We noticed it's been a while since their last cleaning and exam — we'd love to get them back in! We have openings on Tuesday June 11 at 10am or Thursday June 13 at 2pm. Reply YES to confirm or call us at (602) 555-0100. We look forward to seeing you! 😊`;

    case "treatment-script":
      return `"Hi ${guardian}, this is [Name] from DentBooks Dental calling about ${name}'s treatment plan. Dr. [Provider] wanted me to reach out because there are a couple of things we recommended at the last visit that we want to make sure we take care of before they become bigger concerns. This is a great time to get it done — your ${insurance} should cover a good portion of it. Do you have a few minutes to talk about scheduling?"`;

    case "claims-script":
      return `"Good morning, this is [Name] calling from DentBooks Dental on behalf of patient ${name}, date of birth [DOB]. I'm calling regarding claim number ${patient?.claimNumber ?? "CLAIM-XXXXX"}, submitted on ${patient?.claimDate ?? "XX/XX/XXXX"}, in the amount of $${patient?.claimAmount?.toLocaleString() ?? "0.00"}. I'm following up on the status of this claim and wanted to verify whether any additional information is needed. Can you please provide a reference number for this call? Thank you."`;

    case "commlog":
      return `[${new Date().toLocaleDateString()} ${new Date().toLocaleTimeString()}] - Staff: [Name] — Called ${guardian} at ${phone} regarding ${name}'s ${patient?.workflow === "recall" ? "overdue recall appointment" : patient?.workflow === "treatment" ? "unscheduled treatment plan" : `claim #${patient?.claimNumber}`}. [Left VM / Spoke with guardian / No answer]. ${patient?.attemptCount ? `Attempt #${patient.attemptCount + 1}.` : "First contact."} Next follow-up scheduled for [DATE]. - [STAFF INITIALS]`;

    case "manager-summary":
      return `DAILY SUMMARY — ${new Date().toLocaleDateString()}\n\nTeam Performance:\n• Calls Made: 24 / 40 goal\n• Texts Sent: 18 / 25 goal\n• Appointments Scheduled: 7\n• Revenue Recovered: $10,640\n\nTop Priority Items:\n• Charlotte Moore (Claim #AET-2024-9921) — escalated, needs manager review\n• Isabella Davis — pre-auth approved, ready to schedule $1,840 case\n• Emma Rodriguez — 3rd recall attempt today, escalate if no contact\n\nNotes: Claims queue has 2 high-value unresolved items. Recommend afternoon focus on treatment scheduling.`;

    case "next-action":
      return `RECOMMENDED NEXT ACTION for ${name}:\n\n${patient?.workflow === "recall"
        ? `1. Call ${guardian} at ${phone} — mention specific openings\n2. If no answer: send warm text within 10 minutes\n3. Offer Tuesday 10am or Thursday 2pm as first options\n4. Document attempt #${(patient?.attemptCount ?? 0) + 1} in commlog\n5. ${(patient?.attemptCount ?? 0) >= 2 ? "⚠️ ESCALATE — 3rd attempt reached" : `Set ${3 - (patient?.attemptCount ?? 0)} days follow-up task`}`
        : patient?.workflow === "treatment"
        ? `1. Review ${patient?.treatmentPlan} with provider notes\n2. Confirm pre-auth status: ${patient?.preAuthStatus}\n3. Call ${guardian} — use non-fear language\n4. Discuss estimated OOP: $${((patient?.estimatedValue ?? 0) - (patient?.insuranceEstimate ?? 0)).toLocaleString()}\n5. Offer payment plan if barrier is financial`
        : `1. Pull claim #${patient?.claimNumber} from aging report\n2. Log into payer portal: ${patient?.payerName}\n3. Review denial: "${patient?.denialReason}"\n4. Gather missing documents / narrative\n5. Resubmit with corrections + set 14-day follow-up`}`;

    default:
      return "Generating AI response...";
  }
};
